#!/bin/sh
while read file; do
  case "${1}" in
   "C-c")
	  share="${HOME}/pictures/share"
	  mkdir -p "${share}"
	  cp "${file}" "${share}" -v && notify-send "Copied ${file} to ${share}" ;;
   "C-d")
	  trash="/tmp/deleted-pics"
	  mkdir -p "${trash}"
	  mv "${file}" "${trash}/$file" -v && notify-send "Removed ${file} to ${trash}/${file}" ;;
  esac
done
