#!/bin/sh
while read file
do
        case "$1" in
        "C-c")
                cp "$file" "/home/igor/Pictures/share" -v && notify-send "Copied $file to /home/igor/Pictures/share " ;;
	 "C-d")
	        mv "$file" "/tmp/___$file" -v && notify-send "Removed $file to /tmp/___$file" ;;
        esac
done
