set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required


Plugin 'VundleVim/Vundle.vim'
Plugin 'surround.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-commentary.git' " simple comment/uncomment pluginlugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlp.vim'
Plugin 'benmills/vimux'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set noswapfile
set nopaste
syntax on
set hlsearch
set number
set norelativenumber
set ignorecase
set shiftwidth=2
set foldmethod=manual
set hidden
set laststatus=2
set t_Co=256

set history=500

" toggle paste mode
set pastetoggle=<F2>

" nerd tree - close file browser on file select
let g:NERDTreeQuitOnOpen = 1

" vimux panel height
let g:VimuxHeight = "40"

" let ctrl search inside current dir
let g:ctrlp_working_path_mode = 'c'
" correct folding for xml files, see http://vim.wikia.com/wiki/Vim_as_XML_Editor
let g:xml_syntax_folding=1
autocmd FileType xml setlocal foldmethod=syntax
autocmd FileType xml setlocal foldlevel=100000

" python props
autocmd FileType py setlocal expandtab
autocmd FileType py setlocal shiftwidth=4

colors darkblue
let g:airline_theme='dark'

command! FixSvnPaths %s/\s\/.*plugins/ plugins/
command! FixIdeaPaths %s/^.*plugins/plugins/
command! UpdateCurrentDirectory cd %:p:h

let mapleader=","

" exit insert mode
inoremap jj <Esc>

" exit visual mode
vmap JJ <Esc>

" write buffer
noremap <Leader>s :write<CR>

" disabled arrows
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" buffer next/prev
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>

" nerdtree
nnoremap <S-E> :NERDTreeFind<CR>

"select buffer by f5
nnoremap <F5> :buffers<CR>:buffer<Space> 

" search select text
vmap X y/<C-R>"<CR>

" switch between windows
nmap <Leader>w <C-w>w

" insert python debug info
nmap <Leader>pd  oimport ipdb<Esc>oipdb.set_trace()<Esc>0

" close buffer
nmap <F4> :bd <CR>
nmap <Leader><F4> :bd! <CR>

" exit vim
nmap <Leader>q :q <CR>

" execute open python file
nmap <Leader>vp :w <CR> :VimuxRunCommand("clear; python " . bufname("%")) <CR>

" execute rest client
nmap <Leader>vr :w <CR> :VimuxRunCommand("clear; ./rest_client.py \| less") <CR>

" source ~/.vimrc
nmap <Leader>so :source ~/.vimrc <CR>

function! FormatXml()
  % ! python -c 'import lxml.etree as etree; import sys; 
	\text = etree.tostring(etree.fromstring(sys.stdin.read()), pretty_print=True, encoding="utf-8");
	\ print(text.decode("utf-8"))' 
endfunction

function! ParseRailwayLog()
    /<request>/ !python -c "import sys; import urllib.parse; text = sys.stdin.read(); print(urllib.parse.unquote_plus(text))"
    /<password>/ delete
endfunction	

function! FormatJson()
  %! python -c 'import fileinput, json; print(json.dumps(json.loads("".join(fileinput.input())), sort_keys=True, indent=4, ensure_ascii=False))' 
endfunction

function! FormatSelectedXml()
  '<,'> ! python -c 'import lxml.etree as etree; import sys; 
	\text = etree.tostring(etree.fromstring(sys.stdin.read()), pretty_print=True, encoding="utf-8"); print(text.decode("utf-8"))' 
endfunction

function! PythonTemplate()
  execute "normal o" . "def main():\<CR>    print(1)\<CR>"
  execute "normal! i" . "if __name__ == \"__main__\":\<CR>   main()\<CR>"
endfunction  
