#!/usr/bin/zsh

source /my-tools/dotfiles/bash/zprofile.sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

wmname LG3D
sxhkd 1>/tmp/sxhkd.log 2>&1 &
/my-tools/dotfiles/polybar/bspwm-launch-polybar.sh 
/home/igor/.config/virtual-envs/main/bin/flashfocus &
setxkbmap "us,ru" ",winkeys" "grp:caps_toggle"
udiskie --tray &

if [ "$(hostname)" = "igor-manjaro" ] ; then
  compton &
else
  # picom --blur-background --blur-method dual_kawase --experimental-backends --backend glx &
  picom &
fi

scratchpad_class="scratchpad"
termite --class="$scratchpad_class" -e vim &

. /my-tools/dotfiles/bspwm/desktops.sh

bspc monitor --reset-desktops "$d_0" "$d_1" "$d_2" "$d_3" "$d_4" "$d_5" "$d_6" "$d_7" "$d_8" "$d_9"

bspc config border_width 1
bspc config window_gap 30
bspc config top_padding 30
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#ffffff"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Zathura state=fullscreen focus=on follow=on
bspc rule -a "KeePassXC" state=tiled

bspc rule -a "firefox" desktop="$d_5" follow=on focus=on
bspc rule -a "Firefox" desktop="$d_5" follow=on focus=on

bspc rule -a "wm_class_firefox_slack" desktop="$d_0"
bspc rule -a "wm_class_firefox_whatsapp" desktop="$d_0"

bspc rule -a "jetbrains-idea" desktop="$d_3"
bspc rule -a "jetbrains-idea-ce" desktop="$d_3"
bspc rule -a "jetbrains-pycharm-ce" desktop="$d_6"
bspc rule -a "qutebrowser" desktop="$d_1" follow=on focus=on

bspc rule -a "$scratchpad_class" sticky=on state=floating hidden=on rectangle=1200x900+30+30

# idea start up window
bspc rule -a "java-lang-Thread" desktop="3-IDE"

setup_desktop_file="$HOME/.config/bspwm/setup-desktops.sh"
if [ -f "$setup_desktop_file" ] ; then
  source "$setup_desktop_file"
fi
