#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

wmname LG3D
compton &
sxhkd &
polybar --reload --config=/my-tools/dotfiles/polybar/config ivbuch &
/home/igor/IdeaProjects/dotfiles/polybar/bspwm-launch-polybar.sh &
/home/igor/.config/virtual-envs/main/bin/flashfocus &

bspc monitor VGA-1 -d 1
bspc monitor VGA-2 -d 2
bspc monitor VGA-3 -d 3 CHATS

bspc config border_width 1
bspc config window_gap 15
bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2' focus=on state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled focus=on
bspc rule -a Firefox desktop='^2' monitor=VGA-1

firefox -P "teams" --class="wm_class_firefox_teams" https://teams.microsoft.com
