
- name: install packages
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - git
    - gvim
    - tmux
    - qutebrowser
    - cmus
    - zsh  
    - mutt  
    - feh  
    - iotop  
    - docker
    - docker-compose  
    - unzip
    - xclip
    - w3m
    - lsof
    - sysstat
    - python-pip
    - rxvt-unicode
    - urxvt-perls
    - rofi
    - imagemagick
    - fzf
    - maven
    - gradle
    - jad
    - nodejs
    - npm
    - jdk8-openjdk
    - groovy
    - keepassx2
    - rsync
    - ttf-dejavu
    - alsa-utils
    - automake
    - autoconf
    - fakeroot
    - base-devel
