- name: install packages
  pacman:
    name:
      - git
      - gvim
      - tmux
      - zsh  
      - mutt  
      - feh  
      - iotop  
      - docker
      - docker-compose  
      - unzip
      - xclip
      - lsof
      - sysstat
      - python-pip
      - rofi
      - imagemagick
      - fzf
      - maven
      - gradle
      - groovy
      - rsync
      - ttf-dejavu
      - alsa-utils
      - automake
      - autoconf
      - fakeroot
      - base-devel
      - pandoc
      - traceroute
      # https://github.com/ansible/ansible/issues/24110
      # - dnsutils
      - net-tools
      - gnu-netcat
      - unrar
      - zip
      - ngrep
      - wget
      - meld
      - awesome-terminal-fonts
      - tig
      - compton
      - termite
      - zathura
      - zathura-pdf-poppler
      - arandr
      - mpd
      - mpc
      - ncmpcpp
      - simplescreenrecorder
      - vlc
      - ttf-hack
      - sxiv
      - atool
      - dunst
      - gtk2fontsel
      - task
      - noto-fonts-emoji
      - cronie
      - diff-so-fancy
      - pacman-contrib
      - udiskie
      - borg
      - network-manager-applet
      - powertop
      - acpi
      - lightdm-gtk-greeter
      - dnsutils
      - tlp
      - acpi_call
      - tpacpi-bat
      - bat
      - ufw
      - bspwm
      - sxhkd
      - python-psycopg2
      - blueman
    state: present
    update_cache: yes
  become: yes
  tags:
    - pacman

- name: remove packages
  pacman:
    name: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - cmus
    - keepassx2
  tags:
    - pacman
    - pacman-remove
