
- name: install packages
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - git
    - vim
    - tmux
    - qutebrowser
    - cmus
    - zsh  
    - mutt  
