
- name: install packages
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - git
    - gvim
    - tmux
    - qutebrowser
    - cmus
    - zsh  
    - mutt  
    - feh  
    - iotop  
    - docker
    - docker-compose  
    - unzip
    - xclip
    - w3m
    - lsof
    - sysstat
    - python-pip
    - rofi
    - imagemagick
    - fzf
    - maven
    - gradle
    - jad
    - nodejs
    - npm
    - jdk8-openjdk
    - groovy
    - keepassx2
    - keepassx
    - rsync
    - ttf-dejavu
    - alsa-utils
    - automake
    - autoconf
    - fakeroot
    - base-devel
    - pandoc
    - lynx
    - traceroute
    # https://github.com/ansible/ansible/issues/24110
    # - dnsutils
    - conky
    - net-tools
    - gnu-netcat
    - unrar
    - zip
    - scrot
    - ngrep
    - wget
    - meld
    - awesome-terminal-fonts
    - tig
    - compton
    - termite
    - zathura
    - zathura-pdf-poppler
    - arandr
    - mpd
    - ncmpcpp
    - simplescreenrecorder
    - vlc
