- name: check oh-my-zsh install
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_register
  tags:
    - bash

- name: Set zsh default shell
  shell: chsh -s $(which zsh) igor
  become: yes
  tags:
    - bash

- name: create .bash_aliases file if not exists
  file: 
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"
  tags:
    - bash

- name: touch profile files
  file: 
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: touch
  with_items:
    - .profile
    - .zprofile
  tags:
    - bash

- name: source profile.sh
  lineinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    line: "source /my-tools/dotfiles/bash/zprofile.sh"
    state: present
  with_items:
    - .profile
    - .zprofile
  tags:
    - bash

- name: link exec-scripts folder
  file:
    src: "{{ mytools_path }}/home-infra/dotfiles/exec-scripts"
    dest: "{{ ansible_env.HOME }}/.bin/exec-scripts"
    state: link
  tags:
    - bash

- name: link dotfiles exec-scripts folder
  file:
    src: "{{ mytools_path }}/dotfiles/bash/exec-scripts"
    dest: "{{ ansible_env.HOME }}/.bin/exec-scripts-dotfiles"
    state: link
  tags:
    - bash
