- name: create main directory {{ mytools_path }}
  file:
    path: "/my-tools"
    state: directory
  become: yes
  become_method: sudo
  tags:
    - basic

- name: create links to {{ mytools_path }}/dotfiles and {{ mytools_path }}/ansible
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: yes
  become_method: sudo
  with_items:
    - { "src": "{{ dotfiles_path }}", "dest": "{{ mytools_path }}/dotfiles" }
    - { "src": "{{ home_infa_path }}/ansible", "dest": "{{ mytools_path }}/ansible" }
    - { "src": "{{ home_infa_path }}", "dest": "{{ mytools_path }}/home-infra" }
  tags:
    - basic

- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
  tags:
    - basic

- name: /opt ownership
  file:
    path: /opt
    owner: igor
  become: yes  
  tags:
    - basic

- name: create folders
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - "pictures/wallpapers"
    - "pictures/screenshots"
    - "music/chillout"
    - "documents"
    - "downloads"
    - "movies"
    - ".bin"
  tags:
    - basic
