- name: create main directory {{ mytools_path }}
  file:
    path: "/my-tools"
    state: directory
  become: yes
  become_method: sudo

- name: create links to {{ mytools_path }}/dotfiles and {{ mytools_path }}/ansible
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: yes
  become_method: sudo
  with_items:
    - { "src": "{{ dotfiles_path }}", "dest": "{{ mytools_path }}/dotfiles" }
    - { "src": "{{ homeinfostructure_path }}/ansible", "dest": "{{ mytools_path }}/ansible" }
    - { "src": "{{ homeinfostructure_path }}", "dest": "{{ mytools_path }}/home-infostructure" }

- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: font directory exits
  file:
    path: "{{ ansible_env.HOME }}/.local/share"
    state: directory

- name: link fonts
  file:
    src: "/my-tools/home-infostructure/fonts"
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: link

- name: /opt ownership
  file:
    path: /opt
    owner: igor
  become: yes  

- name: create wallpapers folder
  file:
    path: "{{ ansible_env.HOME }}/Pictures/wallpapers"
    state: directory
