- name: create dunst directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:  
    - ".config/dunst"
  tags:
    - dunst

- name: create config link
  file:
    src: "{{ mytools_path }}/dotfiles/dunst/dunstrc"
    dest: "{{ ansible_env.HOME }}/.config/dunst/dunstrc"
    state: link
  tags:
    - dunst
