- name: font directory exits
  file:
    path: "{{ ansible_env.HOME }}/.local/share"
    state: directory
  tags:
    - fonts

- name: link fonts
  file:
    src: "/my-tools/home-infra/fonts"
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: link
  tags:
    - fonts

- name: link fonts
  file:
    src: "/my-tools/home-infra/fonts/desktop"
    path: "{{ ansible_env.HOME }}/.fonts"
    state: link
  tags:
    - fonts

- name: clear fonts cache
  shell: fc-cache -f
  changed_when: no
  tags:
    - fonts
