- name: check install
  stat:
    path: ~/.fzf
  register: fzf_register
  tags:
    - fzf

- name: Cloning repository
  git:
    repo=https://github.com/junegunn/fzf.git
    dest=~/.fzf
    depth=1
  when: fzf_register.stat.exists == false
  tags:
    - fzf
