- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
  with_items:
    - "git"
    - "tig"
  tags:
    - git

- name: link config file
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item.dst }}"
    state: link
  with_items:
    - { "src": "git/git-config", "dst": "git/config" }
    - { "src": "tig/tig-config", "dst": "tig/config" }
  tags:
    - git
