- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
  tags:
    - git

- name: link config file
  file:
    src: "{{ mytools_path }}/dotfiles/git/gitconfig"
    dest: "{{ ansible_env.HOME }}/.config/git/config"
    state: link
  tags:
    - git
