- name: create i3 directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:  
    - ".config/i3"
    - ".config/i3blocks"
  tags:
    - "i3"

- name: create config link
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item }}/config"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}/config"
    state: link
  with_items:
    - i3
    - i3blocks
  tags:
    - "i3"

- name: create log directory
  file:
    path: "/var/log/set-random-themes-logs"
    state: directory
    owner: igor
  become: yes
  become_method: sudo
  tags:
    - "i3"

- name: create set random theme service
  file:
    src: "{{ mytools_path }}/dotfiles/i3/theme-changer/set-random-theme.service"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/set-random-theme.service"
    state: link
  tags:
    - "i3"

- name: create set random theme timer service
  file:
    src: "{{ mytools_path }}/dotfiles/i3/theme-changer/set-random-theme.timer"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/set-random-theme.timer"
    state: link
  tags:
    - "i3"

- name: enable set-random-theme units
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    user: yes
  changed_when: false
  with_with_items:
    - "set-random-theme.service"
    - "set-random-theme.timer"
  tags:
    - "i3"
