- name: remove lightdm-gtk config file
  file:
    path: "/etc/lightdm/lightdm-gtk-greeter.conf"
    state: absent
  become: yes
  tags:
    - lightdm

- name: create config file links
  file:
    src: "{{ mytools_path }}/dotfiles/lightdm/lightdm-gtk-greeter.conf"
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    state: link
  become: yes
  tags:
    - lightdm

- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/lightdm"
    dest: "/etc/lightdm/lightdm-dotfiles"
    state: link
  become: yes
  tags:
    - lightdm

- name: Remove gtk setting
  lineinfile:
    path: "/etc/lightdm/lightdm.conf"
    regexp: "^greeter-session=.*"
    state: absent
  become: yes
  tags:
    - lightdm

- name: Add gtk setting
  lineinfile:
    path: "/etc/lightdm/lightdm.conf"
    line: "greeter-session=lightdm-gtk-greeter"
    insertafter: "^.Seat"
  become: yes
  tags:
    - lightdm
