- import_tasks: basic.yml
- import_tasks: urxvt.yml
- import_tasks: mutt.yml
- import_tasks: vim.yml
- import_tasks: tmux.yml
- import_tasks: python.yml
- import_tasks: i3.yml
- import_tasks: ansible.yml
- import_tasks: ranger.yml
- import_tasks: bash.yml
- import_tasks: qutebrowser.yml
- import_tasks: translate.yml
- import_tasks: git.yml
- import_tasks: ssh.yml
- import_tasks: systemd.yml
