- import_tasks: basic.yml
- import_tasks: termite.yml
- import_tasks: mutt.yml
- import_tasks: vim.yml
- import_tasks: tmux.yml
- import_tasks: python.yml
- import_tasks: systemd.yml
- import_tasks: ansible.yml
- import_tasks: ranger.yml
- import_tasks: bash.yml
- import_tasks: qutebrowser.yml
- import_tasks: git.yml
- import_tasks: ssh.yml
- import_tasks: mongodb.yml
- import_tasks: fonts.yml
- import_tasks: fzf.yml
- import_tasks: psql.yml
- import_tasks: udev.yml
- import_tasks: mpd.yml
- import_tasks: ncmpcpp.yml
- import_tasks: compton.yml
- import_tasks: dunst.yml
- import_tasks: pylint.yml
- import_tasks: rofi.yml
- import_tasks: gtk-3_0.yml
- import_tasks: buku.yml
- import_tasks: lightdm.yml
- import_tasks: jrnl.yml
- import_tasks: bspwm.yml
- import_tasks: sxhkd.yml
- import_tasks: sxiv.yml
