- name: create mutt directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - ".mutt"
    - ".mutt/cache"
    - ".mutt/cache/headers"
    - ".mutt/cache/bodies"
    - ".mutt/cache/certificates"
    - "Downloads/mutt"

- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items:
    - {src: "mutt/muttrc", dest: ".mutt/muttrc" }
    - {src: "mutt/color-scheme", dest: ".mutt/color-scheme" }
      
- name: create mailcap link on macos machine
  file:
    src: "{{ mytools_path }}/dotfiles/mutt/mailcap"
    dest: "{{ ansible_env.HOME }}/.mutt/mailcap"
    state: link
  when: is_mac_os
