- name: create mutt directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - ".mutt"
    - ".mutt/cache"
    - ".mutt/cache/headers"
    - ".mutt/cache/bodies"
    - ".mutt/cache/certificates"
    - "Downloads/mutt"
  tags:
    - mutt

- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items:
    - {src: "mutt/muttrc", dest: ".mutt/muttrc" }
    - {src: "mutt/color-scheme", dest: ".mutt/color-scheme" }
    - {src: "mutt/mailcap", dest: ".mutt/mailcap" }
  tags:
    - mutt
