- name: create link to quteconfig (unix)
  file:
    src: "{{ home_infa_path }}/dotfiles/qutebrowser"
    dest: "{{ ansible_env.HOME }}/.config/qutebrowser"
    state: link
  tags:
    - qutebrowser

- name: create download temp directory
  file:
    path: "{{ ansible_env.HOME }}/downloads/temp"
    state: directory
  tags:
    - qutebrowser
