- name: create link to quteconfig (unix)
  file:
    src: "{{ homeinfostructure_path }}/ansible/playbooks/home/dot-files/qutebrowser"
    dest: "{{ ansible_env.HOME }}/.config/qutebrowser"
    state: link
  when: not is_mac_os

- name: create link to quteconfig
  file:
    src: "{{ homeinfostructure_path }}/ansible/playbooks/home/dot-files/qutebrowser"
    dest: "{{ ansible_env.HOME }}/.qutebrowser"
    state: link
  when: is_mac_os

- name: create download temp directory
  file:
    path: "{{ ansible_env.HOME }}/Downloads/temp"
    state: directory
