- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh/control"
    state: directory
  tags:
    - ssh

- name: create link to ~/.ssh/config
  file:
    src: "{{ home_infa_path }}/dotfiles/ssh-config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
  tags:
    - ssh
