- name: create directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: create link to ~/.ssh/config
  file:
    src: "{{ mytools_path }}/home-infostructure/ansible/playbooks/home/dot-files/ssh-config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
