- name: create system directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:  
    - ".config/systemd"
    - ".config/systemd/user"
  tags:
    - systemd

- name: copy rc-local.service
  copy:
    src: "{{ mytools_path }}/home-infostructure/dotfiles/rc-local/rc-local.service"
    dest: "/usr/lib/systemd/system/rc-local.service"
    remote_src: yes
  become: yes
  become_method: sudo
  tags:
    - systemd

- name: link rc.local script
  file:
    src: "{{ mytools_path }}/home-infostructure/dotfiles/rc-local/rc.local"
    dest: "/etc/rc.local"
    state: link
  become: yes
  tags:
    - systemd

- name: enable services
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
    # - rc-local
  tags:
    - systemd
