- name: create system directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:  
    - ".config/systemd"
    - ".config/systemd/user"
  tags:
    - systemd

- name: copy rc-local.service
  copy:
    src: "{{ mytools_path }}/home-infra/dotfiles/rc-local/rc-local.service"
    dest: "/usr/lib/systemd/system/rc-local.service"
    remote_src: yes
  become: yes
  become_method: sudo
  tags:
    - systemd

- name: link rc.local script
  file:
    src: "{{ mytools_path }}/home-infra/dotfiles/rc-local/rc.local"
    dest: "/etc/rc.local"
    state: link
  become: yes
  tags:
    - systemd

- name: enable services
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  changed_when: true
  with_items:
    - NetworkManager
    - docker
  tags:
    - systemd

- name: Enable Services Arch Linux Only
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  changed_when: true
  with_items:
    - paccache.timer
  when:
    - ansible_facts['distribution'] == "Arch"
  tags:
    - systemd

- name: link user services
  file:
    src: "{{ mytools_path }}/dotfiles/systemd/user-services/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: link
  with_items:
    - on-boot.service
    - blueman-applet.service
    - nm-applet.service
    - volume-icon-applet.service
    - greenclip.service
    - syncthing.service
    - set-random-theme.service
    - set-random-theme.timer
  tags:
    - systemd

- name: enable user services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  with_items:
    - autorandr.service
    - blueman-applet.service 
    - nm-applet.service
    - greenclip.service
    - syncthing.service
    - volume-icon-applet.service
    - on-boot.service
    - set-random-theme.service
    - set-random-theme.timer
  tags:
    - systemd

- name: create powertop service
  copy:
    src: "{{ mytools_path }}/dotfiles/systemd/system-services/powertop.service"
    dest: "/etc/systemd/system/powertop.service"
  become: yes
  tags:
    - systemd

- name: enable system services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - tlp.service
    - powertop.service
  tags:
    - systemd
