- name: create system directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:  
    - ".config/systemd"
    - ".config/systemd/user"
  tags:
    - systemd

- name: copy rc-local.service
  copy:
    src: "{{ mytools_path }}/home-infostructure/dotfiles/rc-local/rc-local.service"
    dest: "/usr/lib/systemd/system/rc-local.service"
    remote_src: yes
  become: yes
  become_method: sudo
  tags:
    - systemd

- name: link rc.local script
  file:
    src: "{{ mytools_path }}/home-infostructure/dotfiles/rc-local/rc.local"
    dest: "/etc/rc.local"
    state: link
  become: yes
  tags:
    - systemd

- name: enable services
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  changed_when: true
  with_items:
    - docker
    - paccache.timer
  tags:
    - systemd

- name: create nm-applet service
  file:
    src: "{{ mytools_path }}/dotfiles/systemd/nm-applet.service"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/nm-applet.service"
    state: link
  tags:
    - systemd

- name: create powertop service
  copy:
    src: "{{ mytools_path }}/dotfiles/systemd/powertop.service"
    dest: "/etc/systemd/system/powertop.service"
  become: yes
  tags:
    - systemd

- name: enable user services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  with_items:
    - nm-applet.service
  tags:
    - systemd

- name: enable system services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - tlp.service
    - tlp-sleep.service
    - powertop.service
  tags:
    - systemd
