- name: create conf link
  file:
    src: "{{ mytools_path }}/dotfiles/tmux/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link

- name: create tmuxp directory
  file:
    src: "{{ mytools_path }}/home-infostructure/tmuxp"
    dest: "{{ ansible_env.HOME }}/.tmuxp"
    state: link

- name: check virtual_env
  stat:
    path: "~/.tmux/plugins/tpm"
  register: tpm_check

- name: clone tmux plugin manager
  command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm  
  when: tpm_check.stat.exists == false
