- name: create .vim directory
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory
  tags:
    - vim

- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  tags:
    - vim
  with_items:
    - {src: "vim/vimrc", dest: ".vimrc" }
    - {src: "vim/ideavimrc", dest: ".ideavimrc" }
    - {src: "vim/colors", dest: ".vim/colors" }

- name: check Vundle
  stat:
    path: ~/.vim/bundle/Vundle.vim
  register: vundle_register
  tags:
    - vim

- name: clone Vundle from git
  shell: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  when: not vundle_register.stat.exists
  tags:
    - vim
