- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items:
    - {src: "vim/vimrc", dest: ".vimrc" }
    - {src: "vim/ideavimrc", dest: ".ideavimrc" }

- name: check Vundle
  stat:
    path: ~/.vim/bundle/Vundle.vim
  register: vundle_register

- name: clone Vundle from git
  shell: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  when: vundle_register.stat.exists == false
