- name: create file links
  file:
    src: "{{ mytools_path }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items:
    - {src: "vim/vimrc", dest: ".vimrc" }
    - {src: "vim/ideavimrc", dest: ".ideavimrc" }
