alias weather="curl wttr.in"
alias svns="svn status | grep -v -E '^Performing' | grep -v -E '^X.*'  | grep -v -E '^$'"
alias svnd="svn diff"
alias tma="python /my-tools/home-infostructure/python-scripts/tmux/tmux-attach-session.py"
