alias weather="curl wttr.in"
alias svns="svn status | grep -v -E '^Performing' | grep -v -E '^X.*'  | grep -v -E '^$'"
alias svnd="svn diff"
alias tma="/my-tools/home-infostructure/python-scripts/tmux/tmux-attach-session.py"
alias gite="/my-tools/home-infostructure/python-scripts/git/git-editor.py"
alias ranger='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'
alias r='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'
alias gd='git difftool'
alias gs='git status'
alias ja='jira-accident-folder.sh'
alias ll="ls -lht"
alias e="exit"
alias _="sudo"
alias cdd="cd /my-tools/dotfiles"
alias cdh="cd /my-tools/home-infostructure"
